### ISSUE TITLE
Broken tex example on escher-jl.org

### ISSUE THREAD

**Issue by astrieanna** [shashi/Escher.jl#90] opened 2015-09-20 04:05 UTC
This is one of the first examples on the escher-jl.org homepage, and it doesn't work.
~~~.jl
function main(window)
    push!(window.assets, "tex")

    tex("""f(x) = \int_{-\infty}^\infty
        \hat f(\xi)\,e^{2 \pi i \xi x}
        \,d\xi""")
end
~~~

When run, it gives this error message (in the browser window):
~~~
LoadError: syntax: invalid escape sequence
while loading /Users/leah/src/learning-julia/code/escher-files/hello.jl, in expression starting on line 24
 in loadfile at /Users/leah/.julia/v0.4/Escher/src/cli/serve.jl:26
 in anonymous at /Users/leah/.julia/v0.4/Escher/src/cli/serve.jl:205
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:15
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:8
 in splitquery at /Users/leah/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/leah/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/leah/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/leah/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/leah/.julia/v0.4/WebSockets/src/WebSockets.jl:354
 in on_message_complete at /Users/leah/.julia/v0.4/HttpServer/src/HttpServer.jl:393
 in on_message_complete at /Users/leah/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/leah/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/leah/.julia/v0.4/HttpServer/src/HttpServer.jl:365
 in anonymous at task.jl:448
~~~

I've looked at the code that's actually running (and that does work), and I can't see what the difference is:
~~~.jl
tex_eg = """f(x) = \\int_{-\\infty}^\\infty
    \\hat f(\\xi)\,e^{2 \\pi i \\xi x}
    \\,d\\xi
"""
~~~

I tried adding an extra backslash in front of the `\,e^`, since that was the only place with one `\`, but that did not cause any problems.

**Comment by drjrkuhn** [comment] 2016-02-18 04:31
The triple-quote does not ignore backslash escape sequences. The problem is that the `\x` in `\xi` is interpreted as a hex character code, *not* as a TeX `$\xi$` math character. In fact, `\xi` is interpreted as the hex character `0x0i`, which is not even a valid hex number. So the string interpreter throws `ERROR: syntax: invalid escape sequence`, which gums up Escher completely.

In contrast the `\h` in `\hat` is not a proper Julia string escape code, but it does not generate an error. It is just interpreted as `hat`. The same pass-through behavior appears to be work for `\int`, `\infty`, `\pi`, and `\,`. Just not for `\xi`. Try replacing double backslashes **only** on the `\\xi` escapes. For example:

```julia
using Compose

function main(window)
	push!(window.assets, "tex")
	tex("""f(x) = \int_{-\infty}^\infty
    \hat f(\\xi)\,e^{2 \pi i \\xi x}
    \,d\\xi
	\,\x40""")
end
```

This renders, but with spelled-out *int*, *hat*, and *infty* in the equation rather than their TeX characters. 

(I have added an `ASCII '@'` character (`0x40`) at the end to show the escaped character interpretation within the triple-quote string.)


It might be prudent to change all of the example code to use double escape characters `\\` to be on the safe side.

**Comment by randyzwitch** [comment] 2016-04-12 19:32
I believe this is actually fixed in master `doc/index.jl` @shashi, I just needs to be pushed to escher-jl.org

https://github.com/shashi/Escher.jl/blob/master/docs/index.jl#l49-#L52

**Closed by randyzwitch** 2016-04-12 19:32 UTC
Labels: Documentation, help wanted
