### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by evcastelani** [shashi/Escher.jl#55] opened 2015-07-28 17:05 UTC
Hi! When I try to run and access an example of escher.jl , I have a problem of segment fault...Does anyone know why?

Listening on 0.0.0.0:5555...

signal (11): Falha de segmentação
unknown function (ip: -370066064)
write at /usr/bin/../lib64/julia/sys.so (unknown line)
write at ./iobuffer.jl:235

I am using Fedora 22.

Thanks

**Comment by rohitvarkey** [comment] 2015-07-28 17:19
Hey! Can you tell which example caused this? And what version of Julia are you on?

**Comment by evcastelani** [comment] 2015-07-28 17:28
I'm using julia v0.3.8 and all standard examples are given problems (code.jl, form.jl)...

**Comment by randyzwitch** [comment] 2016-04-12 17:44
Going to close this, if only because so much has changed since 0.3.8. If this is still an issue with newer versions of Julia, please open a new issue with a reproducible example.

Thanks!

**Closed by randyzwitch** 2016-04-12 17:44 UTC
